# Generated by Django 2.2.1 on 2019-08-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='llisting_id',
            new_name='listing_id',
        ),
    ]
